version: "2"
services:
  zookeeper:
    image: confluent/zookeeper:latest
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"

  kafka1:
    hostname: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9092"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka2:9093"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /tmp/docker/kafka2/logs:/logs
      - /tmp/docker/kafka2/data:/data

  kafka3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka3:9094"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /tmp/docker/kafka2/logs:/logs
      - /tmp/docker/kafka2/data:/data

  schema-registry:
    image: confluent/schema-registry:latest
    hostname: schema-registry
    restart: "on-failure:3"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper
    links:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "8081:8081"
    environment:
      SR_KAFKASTORE_CONNECTION_URL: zookeeper:2181

  kafka_tools:
    image: confluent/tools:latest
    links:
      - zookeeper
      - schema-registry
      - kafka1
      - kafka2
      - kafka3
