version: "2"
services:
  zookeeper:
    image: confluent/zookeeper:latest
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"

  kafka:
    hostname: kafka
    image: confluent/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /tmp/docker/kafka1/logs:/logs
      - /tmp/docker/kafka1/data:/data

  rest-proxy:
    image: confluent/rest-proxy:latest
    hostname: rest-proxy
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    ports:
      - "8082:8082"
    environment:
      RP_ZOOKEEPER_CONNECT: "zookeeper:2181"
      RP_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"

  schema-registry:
    image: confluent/schema-registry:latest
    hostname: schema-registry
    restart: "on-failure:3"
    depends_on:
      - kafka
      - zookeeper
    links:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      SR_KAFKASTORE_CONNECTION_URL: zookeeper:2181

  kafka_tools:
    image: confluent/tools:latest
    links:
      - consul
      - zookeeper
      - schema-registry
      - kafka
